let question1 = $("#question1")
let question2 = $("#question2")
let question3 = $("#question3")
let question4 = $("#question4")
let question5 = $("#question5")
let question6 = $("#question6")
let question7 = $("#question7")
let question8 = $("#question8")
let question9 = $("#question9")
let question10 = $("#question10")
// let question1 = $("#question1")
// let question1 = $("#question1")
// let question1 = $("#question1")
function validateForm(){
    question1.each()
    //.isChecked()
}